User profile
sabrasisler/FSE-Final-Project-React pull request #1
Opened 2022-04-07 05:47 UTC by spencersolomon6

#5 - Adds frontend component and service support for displaying another user's profile to the currently authenticated user.

2022-04-11 04:07 UTC, tmudunuri approved these changes

2022-04-12 19:36 UTC, sabrasisler requested changes
Everything looks good except the documentation, which I believe should be done before we merge.

2022-04-12 19:36 UTC, sabrasisler commented on src/components/Tuits/Tuit.js
>  import TuitVideo from './TuitVideo';
Can you make sure to add documentation at the top each file you edit or create?

2022-04-12 19:36 UTC, sabrasisler commented on src/services/users-service.js
>  import axios from 'axios';
Can you make sure to add documentation at the top each file you edit or create?

2022-04-12 19:36 UTC, sabrasisler commented on src/views/OtherUserProfileView/ProfileNav.js
> +import { NavLink } from 'react-router-dom';
Can you make sure to add documentation at the top each file you edit or create?

2022-04-12 19:36 UTC, sabrasisler commented on src/views/OtherUserProfileView/UsersDislikes.js
> +import { useEffect, useState } from 'react';
Can you make sure to add documentation at the top each file you edit or create?

2022-04-13 15:40 UTC, sabrasisler approved these changes
Thanks for updating the documentation. Everything looks good now and should be ready to merge. Diego needs to approve it first though

2022-04-17 23:42 UTC, merged