Follows notification
sabrasisler/FSE-Final-Project-React pull request #11
Opened 2022-04-20 16:27 UTC by sabrasisler

Added ability to link the user's profile who did the action such as following,messaging,or liking within the notification.

2022-04-20 17:48 UTC, creativediego requested changes
Can we remove the unused commented out code and console logs? Can we change var to let? (Var is an anti-pattern). 

Since the test file is a filler right now with commented out code, can we remove the file and make it part of another PR?

2022-04-20 17:50 UTC, spencersolomon6 approved these changes
Approved pending Diego's changes

2022-04-21 19:17 UTC, tmudunuri approved these changes
Looks good.

2022-04-23 17:40 UTC, creativediego approved these changes

2022-04-23 17:46 UTC, merged