Remove mock messages components
sabrasisler/FSE-Final-Project-React pull request #15
Opened 2022-04-21 00:51 UTC by tmudunuri

Delete mock components.

2022-04-21 02:45 UTC, spencersolomon6 requested changes
I think this PR is a duplicate of #16 and can be closed.

2022-04-21 19:14 UTC, tmudunuri commented
> I think this PR is a duplicate of #16 and can be closed.

The intention was to stack PRs to make them easier to read. ie. once this PR is merged, the other PR becomes smaller.

2022-04-21 21:16 UTC, creativediego approved these changes

2022-04-22 00:46 UTC, spencersolomon6 approved these changes

2022-04-22 16:26 UTC, sabrasisler approved these changes

2022-04-22 16:28 UTC, merged