Implement convo and message deletion.
sabrasisler/FSE-Final-Project-React pull request #21
Opened 2022-04-25 07:27 UTC by creativediego

2022-04-25 16:48 UTC, sabrasisler approved these changes

2022-04-25 16:53 UTC, spencersolomon6 approved these changes

2022-04-25 16:53 UTC, spencersolomon6 commented on src/redux/messageThunks.js
> +    // inboxMessages.forEach((inboxMessage) => {
Can this be removed?

2022-04-25 17:25 UTC, tmudunuri approved these changes

2022-04-25 17:31 UTC, tmudunuri requested changes

2022-04-25 17:31 UTC, tmudunuri commented on src/components/Messages/InboxMessage.js
> +            {message &&
We seem to be including the logged-in user here — which is redundant.
![image](https://user-images.githubusercontent.com/23713701/165142421-25e3ffce-ba93-4523-9ae1-2d211b33ec0e.png)

2022-04-26 20:05 UTC, tmudunuri approved these changes

2022-04-26 20:15 UTC, merged